package kg.toilink.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import kg.toilink.dto.request.RsvpRequest;
import kg.toilink.entity.Event;
import kg.toilink.entity.Guest;
import kg.toilink.entity.RsvpResponse;
import kg.toilink.exception.BadRequestException;
import kg.toilink.exception.NotFoundException;
import kg.toilink.repository.EventRepository;
import kg.toilink.repository.GuestRepository;
import kg.toilink.repository.RsvpResponseRepository;
import kg.toilink.util.PhoneUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class RsvpService {

    private final EventRepository eventRepository;
    private final GuestRepository guestRepository;
    private final RsvpResponseRepository rsvpResponseRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Transactional
    public RsvpResult rsvp(String slug, RsvpRequest req) {
        Event event = eventRepository.findBySlug(slug)
                .orElseThrow(() -> NotFoundException.eventBySlug(slug));

        if ("DRAFT".equals(event.getStatus())) {
            throw new BadRequestException("Event is not published yet");
        }
        if ("CLOSED".equals(event.getStatus())) {
            throw new BadRequestException("Event is closed for responses");
        }
        if (event.getRsvpDeadline() != null && LocalDateTime.now().isAfter(event.getRsvpDeadline())) {
            throw new BadRequestException("RSVP deadline has passed");
        }

        Guest guest = resolveGuest(event, req);

        // Spouse companion: only when event explicitly allows it (blocksConfig.rsvp.allowCompanion === true)
        if (isCompanionAllowed(event)) {
            manageSpouseCompanion(guest, event, req.spouseName());
        }

        rsvpResponseRepository.findByGuestIdAndEventId(guest.getId(), event.getId())
                .ifPresentOrElse(
                        existing -> {
                            existing.setStatus(req.status());
                            existing.setGroupSize(req.groupSize() != null && req.groupSize() > 0 ? req.groupSize() : 1);
                            existing.setComment(req.comment());
                            rsvpResponseRepository.save(existing);
                        },
                        () -> rsvpResponseRepository.save(RsvpResponse.builder()
                                .guest(guest)
                                .event(event)
                                .status(req.status())
                                .groupSize(req.groupSize() != null && req.groupSize() > 0 ? req.groupSize() : 1)
                                .comment(req.comment())
                                .build())
                );

        return new RsvpResult(req.status(), guest.getToken());
    }

    /** Result returned to controller — includes guestToken for localStorage persistence */
    public record RsvpResult(String status, java.util.UUID guestToken) {}

    private Guest resolveGuest(Event event, RsvpRequest req) {
        // 1. Token-based match (most precise — guest opens a personal link or returns via localStorage token)
        if (req.guestToken() != null) {
            Guest guest = guestRepository.findByTokenAndDeletedAtIsNull(req.guestToken())
                    .orElseThrow(() -> new BadRequestException("Invalid guest token"));
            if (!guest.getEvent().getId().equals(event.getId())) {
                throw new BadRequestException("Guest token does not belong to this event");
            }
            return applyIncomingFields(guest, req);
        }

        if (req.name() == null || req.name().isBlank()) {
            throw new BadRequestException("Name is required when responding through the public link");
        }

        // 2. Phone-based dedup — find existing guest with same normalized phone in this event
        String normalizedPhone = PhoneUtils.normalize(req.phone());
        if (normalizedPhone != null) {
            Optional<Guest> match = findByNormalizedPhone(event.getId(), normalizedPhone);
            if (match.isPresent()) {
                return applyIncomingFields(match.get(), req);
            }
        }

        // 3. Create new guest — token auto-generated by @PrePersist; group code from validated URL.
        return guestRepository.save(Guest.builder()
                .event(event)
                .name(req.name().trim())
                .phone(req.phone() != null && !req.phone().isBlank() ? req.phone().trim() : null)
                .source("PUBLIC_LINK")
                .side(req.groupCode() != null && !req.groupCode().isBlank() ? req.groupCode() : null)
                .build());
    }

    /**
     * Update an existing guest with incoming RSVP fields.
     * Name is overwritten if non-blank. Phone is filled if missing.
     * Side is overwritten when the URL carries a specific groupCode — we trust the URL.
     * Source is never downgraded (PERSONAL_LINK stays PERSONAL_LINK even if guest opens public link).
     */
    private Guest applyIncomingFields(Guest guest, RsvpRequest req) {
        boolean changed = false;
        if (req.name() != null && !req.name().isBlank()) {
            guest.setName(req.name().trim());
            changed = true;
        }
        if (req.phone() != null && !req.phone().isBlank()
                && (guest.getPhone() == null || guest.getPhone().isBlank())) {
            guest.setPhone(req.phone().trim());
            changed = true;
        }
        if (req.groupCode() != null && !req.groupCode().isBlank()
                && !Objects.equals(req.groupCode(), guest.getSide())) {
            guest.setSide(req.groupCode());
            changed = true;
        }
        return changed ? guestRepository.save(guest) : guest;
    }

    private Optional<Guest> findByNormalizedPhone(Long eventId, String normalizedPhone) {
        List<Guest> candidates = guestRepository.findAllWithPhoneByEventId(eventId);
        for (Guest g : candidates) {
            if (normalizedPhone.equals(PhoneUtils.normalize(g.getPhone()))) {
                return Optional.of(g);
            }
        }
        return Optional.empty();
    }

    /** Reads event.blocksConfig.rsvp.allowCompanion (boolean). Default: false. */
    private boolean isCompanionAllowed(Event event) {
        String blocksConfig = event.getBlocksConfig();
        if (blocksConfig == null || blocksConfig.isBlank()) return false;
        try {
            JsonNode root = objectMapper.readTree(blocksConfig);
            JsonNode flag = root.path("rsvp").path("allowCompanion");
            return flag.isBoolean() && flag.asBoolean();
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Manage the auto-created spouse companion for a primary guest.
     * - spouseName non-blank → create or update auto-companion (source = COMPANION_AUTO).
     * - spouseName blank/null → delete existing auto-companion (manual companions added by organizer are untouched).
     * Companion inherits side from primary.
     */
    private void manageSpouseCompanion(Guest primary, Event event, String spouseName) {
        Guest existingAuto = findAutoCompanion(primary);

        if (spouseName != null && !spouseName.isBlank()) {
            String trimmed = spouseName.trim();
            if (existingAuto != null) {
                if (!Objects.equals(existingAuto.getName(), trimmed)
                        || !Objects.equals(existingAuto.getSide(), primary.getSide())) {
                    existingAuto.setName(trimmed);
                    existingAuto.setSide(primary.getSide());
                    guestRepository.save(existingAuto);
                }
                return;
            }
            Guest companion = guestRepository.save(Guest.builder()
                    .event(event)
                    .name(trimmed)
                    .source("COMPANION_AUTO")
                    .side(primary.getSide())
                    .relatedToId(primary.getId())
                    .relationType("SPOUSE")
                    .build());
            primary.setRelatedToId(companion.getId());
            primary.setRelationType("SPOUSE");
            guestRepository.save(primary);
            return;
        }

        // spouseName blank → remove auto-companion if it exists; manual companions are kept.
        if (existingAuto != null) {
            if (Objects.equals(primary.getRelatedToId(), existingAuto.getId())) {
                primary.setRelatedToId(null);
                primary.setRelationType(null);
                guestRepository.save(primary);
            }
            guestRepository.delete(existingAuto);
        }
    }

    /** Returns the auto-created companion linked to the primary guest, if any. */
    private Guest findAutoCompanion(Guest primary) {
        if (primary.getRelatedToId() != null) {
            Optional<Guest> related = guestRepository.findById(primary.getRelatedToId());
            if (related.isPresent() && "COMPANION_AUTO".equals(related.get().getSource())
                    && related.get().getDeletedAt() == null) {
                return related.get();
            }
        }
        // Fallback: search all guests of the event for an auto-companion pointing at primary.
        // (Covers cases where primary.relatedToId points to a manual companion but an auto exists too.)
        for (Guest g : guestRepository.findAllByEventId(primary.getEvent().getId())) {
            if ("COMPANION_AUTO".equals(g.getSource())
                    && primary.getId().equals(g.getRelatedToId())) {
                return g;
            }
        }
        return null;
    }
}
