package kg.toilink.service;

import kg.toilink.dto.request.RsvpRequest;
import kg.toilink.entity.Event;
import kg.toilink.entity.Guest;
import kg.toilink.entity.RsvpResponse;
import kg.toilink.exception.BadRequestException;
import kg.toilink.exception.NotFoundException;
import kg.toilink.repository.EventRepository;
import kg.toilink.repository.GuestRepository;
import kg.toilink.repository.RsvpResponseRepository;
import kg.toilink.util.PhoneUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class RsvpService {

    private final EventRepository eventRepository;
    private final GuestRepository guestRepository;
    private final RsvpResponseRepository rsvpResponseRepository;

    @Transactional
    public RsvpResult rsvp(String slug, RsvpRequest req) {
        Event event = eventRepository.findBySlug(slug)
                .orElseThrow(() -> NotFoundException.eventBySlug(slug));

        if ("DRAFT".equals(event.getStatus())) {
            throw new BadRequestException("Event is not published yet");
        }
        if ("CLOSED".equals(event.getStatus())) {
            throw new BadRequestException("Event is closed for responses");
        }
        if (event.getRsvpDeadline() != null && LocalDateTime.now().isAfter(event.getRsvpDeadline())) {
            throw new BadRequestException("RSVP deadline has passed");
        }

        Guest guest = resolveGuest(event, req);

        rsvpResponseRepository.findByGuestIdAndEventId(guest.getId(), event.getId())
                .ifPresentOrElse(
                        existing -> {
                            existing.setStatus(req.status());
                            existing.setGroupSize(req.groupSize() != null && req.groupSize() > 0 ? req.groupSize() : 1);
                            existing.setComment(req.comment());
                            rsvpResponseRepository.save(existing);
                        },
                        () -> rsvpResponseRepository.save(RsvpResponse.builder()
                                .guest(guest)
                                .event(event)
                                .status(req.status())
                                .groupSize(req.groupSize() != null && req.groupSize() > 0 ? req.groupSize() : 1)
                                .comment(req.comment())
                                .build())
                );

        return new RsvpResult(req.status(), guest.getToken());
    }

    /** Result returned to controller — includes guestToken for localStorage persistence */
    public record RsvpResult(String status, java.util.UUID guestToken) {}

    private Guest resolveGuest(Event event, RsvpRequest req) {
        // 1. Token-based match (most precise — guest opens a personal link or returns via localStorage token)
        if (req.guestToken() != null) {
            Guest guest = guestRepository.findByTokenAndDeletedAtIsNull(req.guestToken())
                    .orElseThrow(() -> new BadRequestException("Invalid guest token"));
            if (!guest.getEvent().getId().equals(event.getId())) {
                throw new BadRequestException("Guest token does not belong to this event");
            }
            return applyIncomingFields(guest, req);
        }

        if (req.name() == null || req.name().isBlank()) {
            throw new BadRequestException("Name is required when responding through the public link");
        }

        // 2. Phone-based dedup — find existing guest with same normalized phone in this event
        String normalizedPhone = PhoneUtils.normalize(req.phone());
        if (normalizedPhone != null) {
            Optional<Guest> match = findByNormalizedPhone(event.getId(), normalizedPhone);
            if (match.isPresent()) {
                return applyIncomingFields(match.get(), req);
            }
        }

        // 3. Create new guest — token auto-generated by @PrePersist; group code from validated URL.
        return guestRepository.save(Guest.builder()
                .event(event)
                .name(req.name().trim())
                .phone(req.phone() != null && !req.phone().isBlank() ? req.phone().trim() : null)
                .source("PUBLIC_LINK")
                .side(req.groupCode() != null && !req.groupCode().isBlank() ? req.groupCode() : null)
                .build());
    }

    /**
     * Update an existing guest with incoming RSVP fields.
     * Name is overwritten if non-blank. Phone is filled if missing.
     * Side is overwritten when the URL carries a specific groupCode — we trust the URL.
     * Source is never downgraded (PERSONAL_LINK stays PERSONAL_LINK even if guest opens public link).
     */
    private Guest applyIncomingFields(Guest guest, RsvpRequest req) {
        boolean changed = false;
        if (req.name() != null && !req.name().isBlank()) {
            guest.setName(req.name().trim());
            changed = true;
        }
        if (req.phone() != null && !req.phone().isBlank()
                && (guest.getPhone() == null || guest.getPhone().isBlank())) {
            guest.setPhone(req.phone().trim());
            changed = true;
        }
        if (req.groupCode() != null && !req.groupCode().isBlank()
                && !Objects.equals(req.groupCode(), guest.getSide())) {
            guest.setSide(req.groupCode());
            changed = true;
        }
        return changed ? guestRepository.save(guest) : guest;
    }

    private Optional<Guest> findByNormalizedPhone(Long eventId, String normalizedPhone) {
        List<Guest> candidates = guestRepository.findAllWithPhoneByEventId(eventId);
        for (Guest g : candidates) {
            if (normalizedPhone.equals(PhoneUtils.normalize(g.getPhone()))) {
                return Optional.of(g);
            }
        }
        return Optional.empty();
    }
}
