spring:
  application:
    name: toilink

  datasource:
    url: jdbc:postgresql://localhost:5432/toilink
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: INFO
server:
  port: 9999