spring:
  application:
    name: toilink

  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-cache: true
          must-revalidate: true

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:toilink}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

app:
  upload-dir: uploads

logging:
  level:
    liquibase: INFO
server:
  port: ${PORT:8888}